delete items
Andromeda-Learning/vanilla-todo-app-Anzormumladze pull request #2
Opened 2020-03-06 21:26 UTC by Anzormumladze

2020-03-07 13:14 UTC, shavidzet requested changes

2020-03-07 13:14 UTC, shavidzet commented on app.js
> +const deleteMovieHandler = e => e.target.remove();
This function doesn't return anything, so please wrap with curly braces/brackets

2020-03-08 15:46 UTC, DakoMumladze requested changes

2020-03-08 15:46 UTC, DakoMumladze commented on app.js
> +  let list = document.querySelector("#list");
ამ ობიექტის მნიშვნელობა არ შეიცვლება და const უნდა გქონდეს let-ების ნაცვლად.

2020-03-08 15:55 UTC, DakoMumladze submitted a review, later dismissed

2020-03-08 16:29 UTC, DakoMumladze approved these changes

2020-03-08 16:31 UTC, shavidzet approved these changes

2020-03-08 16:32 UTC, DakoMumladze approved these changes

2020-03-08 16:33 UTC, DakoMumladze approved these changes

2020-03-08 16:54 UTC, merged