Feature/rename items
Andromeda-Learning/vanilla-todo-app-Anzormumladze pull request #4
Opened 2020-03-09 17:51 UTC by Anzormumladze

changing items name with button click

2020-03-10 08:14 UTC, DakoMumladze submitted a review, later dismissed

2020-03-10 20:22 UTC, shavidzet requested changes

2020-03-10 20:22 UTC, shavidzet commented on app.js
> +  e.target.parentNode.firstChild.textContent = prompt("change items name");
querySelector ან რამე იხმარე, დომის ხე რო შეიცვლება დაიქრაშება ინტერფეისი

2020-03-13 11:38 UTC, Anzormumladze commented on app.js
> +  e.target.parentNode.firstChild.textContent = prompt("change items name");
jquery გამოყენება მომიწევს რომ მივწვდე li ტექსტს და დომის ხის დაქრაშვა არ ემუქრება ამ თასქში რადგან მეტი ფუნქციონალის დამატება არ მოგივწევს შესაბამისად არც ელემენტები დაემატება ,button ზე კლიკით მშობელს ვწვდები და მშობლიდან პირველ შვილს რომელიც სულ li ტექსტი ,უნდა იჩალიჩო რომ li ტექსტის მაგივრად სხვა რამე ჩასვა

2020-03-13 18:12 UTC, shavidzet commented on app.js
> +  e.target.parentNode.firstChild.textContent = prompt("change items name");
`e.target.parentNode.querySelector('li')` აჯობებს

2020-03-13 18:17 UTC, shavidzet commented on app.js
> +  if (e.target && e.target.nodeName === "BUTTON") {
ეს რა საჭიროა საერთოდ?

2020-03-16 17:38 UTC, Anzormumladze commented on app.js
> +  e.target.parentNode.firstChild.textContent = prompt("change items name");
e.target.parentNode უკვე li თაგს წვდება და .querySelector('li')  ეს რა საჭიროა ?  e.target.parentNode.firstChild ამ კოდის li თაგში არსებულ პირველ ინდექსზე მყოფ ტექსტს ვწვდები

2020-03-16 17:40 UTC, Anzormumladze commented on app.js
> +  if (e.target && e.target.nodeName === "BUTTON") {
ეს მოვაშორე

2026-06-11 15:20 UTC, closed without merging